"""Initial schema

Revision ID: 06e7235cba5a
Revises: 
Create Date: 2025-10-31 13:04:18.234919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06e7235cba5a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtests',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('ix_backtests_started_at', 'backtests', ['started_at'], unique=False)
    op.create_table('features',
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('dt', sa.Date(), nullable=False),
    sa.Column('features_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('label_ret_1d', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('ticker', 'dt')
    )
    op.create_index('ix_features_dt', 'features', ['dt'], unique=False)
    op.create_index('ix_features_ticker', 'features', ['ticker'], unique=False)
    op.create_table('fundamentals',
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('asof', sa.Date(), nullable=False),
    sa.Column('pe', sa.Float(), nullable=True),
    sa.Column('pb', sa.Float(), nullable=True),
    sa.Column('ev_ebitda', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('roce', sa.Float(), nullable=True),
    sa.Column('de_ratio', sa.Float(), nullable=True),
    sa.Column('eps_g3y', sa.Float(), nullable=True),
    sa.Column('rev_g3y', sa.Float(), nullable=True),
    sa.Column('profit_g3y', sa.Float(), nullable=True),
    sa.Column('opm', sa.Float(), nullable=True),
    sa.Column('npm', sa.Float(), nullable=True),
    sa.Column('div_yield', sa.Float(), nullable=True),
    sa.Column('promoter_hold', sa.Float(), nullable=True),
    sa.Column('pledged_pct', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('ticker', 'asof')
    )
    op.create_index('ix_fundamentals_asof', 'fundamentals', ['asof'], unique=False)
    op.create_index('ix_fundamentals_ticker', 'fundamentals', ['ticker'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dt', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('sent_pos', sa.Float(), nullable=False),
    sa.Column('sent_neg', sa.Float(), nullable=False),
    sa.Column('sent_comp', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_news_dt', 'news', ['dt'], unique=False)
    op.create_index('ix_news_ticker', 'news', ['ticker'], unique=False)
    op.create_index('ix_news_ticker_dt', 'news', ['ticker', 'dt'], unique=False)
    op.create_table('preds',
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('dt', sa.Date(), nullable=False),
    sa.Column('horizon', sa.String(length=50), nullable=False),
    sa.Column('yhat', sa.Float(), nullable=False),
    sa.Column('yhat_std', sa.Float(), nullable=False),
    sa.Column('prob_up', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'dt', 'horizon')
    )
    op.create_index('ix_preds_dt', 'preds', ['dt'], unique=False)
    op.create_index('ix_preds_ticker', 'preds', ['ticker'], unique=False)
    op.create_index('ix_preds_ticker_dt', 'preds', ['ticker', 'dt'], unique=False)
    op.create_table('prices',
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('dt', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(), nullable=False),
    sa.Column('high', sa.Numeric(), nullable=False),
    sa.Column('low', sa.Numeric(), nullable=False),
    sa.Column('close', sa.Numeric(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('adj_close', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'dt')
    )
    op.create_index('ix_prices_dt', 'prices', ['dt'], unique=False)
    op.create_index('ix_prices_ticker', 'prices', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prices_ticker', table_name='prices')
    op.drop_index('ix_prices_dt', table_name='prices')
    op.drop_table('prices')
    op.drop_index('ix_preds_ticker_dt', table_name='preds')
    op.drop_index('ix_preds_ticker', table_name='preds')
    op.drop_index('ix_preds_dt', table_name='preds')
    op.drop_table('preds')
    op.drop_index('ix_news_ticker_dt', table_name='news')
    op.drop_index('ix_news_ticker', table_name='news')
    op.drop_index('ix_news_dt', table_name='news')
    op.drop_table('news')
    op.drop_index('ix_fundamentals_ticker', table_name='fundamentals')
    op.drop_index('ix_fundamentals_asof', table_name='fundamentals')
    op.drop_table('fundamentals')
    op.drop_index('ix_features_ticker', table_name='features')
    op.drop_index('ix_features_dt', table_name='features')
    op.drop_table('features')
    op.drop_index('ix_backtests_started_at', table_name='backtests')
    op.drop_table('backtests')
    # ### end Alembic commands ###
